# Generated by Django 4.2 on 2025-12-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=255)),
                ('gia', models.IntegerField()),
                ('phan_loai', models.CharField(max_length=100)),
                ('ghi_chu', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
