# Generated by Django 4.2 on 2025-12-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMENU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_danhmuc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_danhmuc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_khach', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('sdt', models.CharField(blank=True, max_length=20, null=True)),
                ('diem_tich_luy', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_mon', models.AutoField(primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=255)),
                ('gia', models.IntegerField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('id_danhmuc', models.ForeignKey(db_column='id_danhmuc', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EMENU.category')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_donhang', models.AutoField(primary_key=True, serialize=False)),
                ('tong_tien', models.IntegerField(default=0)),
                ('trang_thai_tt', models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang làm'), ('ready', 'Đã xong'), ('served', 'Đã phục vụ'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_chitiet', models.AutoField(primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField(default=1)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('da_ra_mon', models.BooleanField(default=False)),
                ('id_donhang', models.ForeignKey(db_column='id_donhang', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EMENU.order')),
                ('id_mon', models.ForeignKey(db_column='id_mon', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='EMENU.item')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_tt', models.AutoField(primary_key=True, serialize=False)),
                ('phuong_thuc', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('banking', 'Chuyển khoản')], max_length=20)),
                ('thoi_gian_tt', models.DateTimeField(auto_now_add=True)),
                ('id_donhang', models.ForeignKey(db_column='id_donhang', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='EMENU.order')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_ban', models.AutoField(primary_key=True, serialize=False)),
                ('so_ban', models.CharField(max_length=50, unique=True)),
                ('trang_thai', models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đã đặt trước'), ('occupied', 'Đang sử dụng')], default='available', max_length=20)),
                ('thoi_gian_dat', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_het_han', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bàn',
                'verbose_name_plural': 'Bàn',
                'db_table': 'tables',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='order',
            name='id_ban',
            field=models.ForeignKey(db_column='id_ban', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='EMENU.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_khach',
            field=models.ForeignKey(blank=True, db_column='id_khach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='EMENU.customer'),
        ),
    ]
