# Generated by Django 4.2 on 2025-12-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMENU', '0002_category_customer_item_order_orderitem_payment_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_khach',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
