# Generated by Django 4.2 on 2025-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMENU', '0003_remove_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_danhmuc',
            field=models.AutoField(db_column='id_danhmuc', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_danhmuc',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='ten_danhmuc',
            field=models.CharField(db_column='ten_danhmuc', max_length=100),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ten_danhmuc',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id_danhmuc',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='id_mon',
            field=models.AutoField(db_column='id_mon', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id_mon',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='hinh_anh',
            field=models.ImageField(blank=True, db_column='hinh_anh', null=True, upload_to='menu/'),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='hinh_anh',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='ten_mon',
            field=models.CharField(db_column='ten_mon', max_length=255),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ten_mon',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='gia',
            field=models.IntegerField(db_column='gia'),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gia',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='id_donhang',
            field=models.AutoField(db_column='id_donhang', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_donhang',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='trang_thai_tt',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang làm'), ('ready', 'Đã xong'), ('served', 'Đã phục vụ'), ('cancelled', 'Đã hủy')], db_column='trang_thai_tt', default='pending', max_length=20),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='trang_thai_tt',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_ban',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='order',
            name='tong_tien',
            field=models.IntegerField(db_column='tong_tien', default=0),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tong_tien',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id_chitiet',
            field=models.AutoField(db_column='id_chitiet', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_chitiet',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='da_ra_mon',
            field=models.BooleanField(db_column='da_ra_mon', default=False),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='da_ra_mon',
            new_name='is_served',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_mon',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ghi_chu',
            field=models.TextField(blank=True, db_column='ghi_chu', null=True),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ghi_chu',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_donhang',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='so_luong',
            field=models.IntegerField(db_column='so_luong', default=1),
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='so_luong',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id_tt',
            field=models.AutoField(db_column='id_tt', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id_tt',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='phuong_thuc',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('banking', 'Chuyển khoản')], db_column='phuong_thuc', max_length=20),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='phuong_thuc',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id_donhang',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='payment',
            name='thoi_gian_tt',
            field=models.DateTimeField(auto_now_add=True, db_column='thoi_gian_tt'),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='thoi_gian_tt',
            new_name='paid_at',
        ),
        migrations.AlterField(
            model_name='table',
            name='thoi_gian_het_han',
            field=models.DateTimeField(blank=True, db_column='thoi_gian_het_han', null=True),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='thoi_gian_het_han',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='table',
            name='id_ban',
            field=models.AutoField(db_column='id_ban', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='id_ban',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='so_ban',
            field=models.CharField(db_column='so_ban', max_length=50, unique=True),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='so_ban',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='table',
            name='thoi_gian_dat',
            field=models.DateTimeField(blank=True, db_column='thoi_gian_dat', null=True),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='thoi_gian_dat',
            new_name='reserved_at',
        ),
        migrations.AlterField(
            model_name='table',
            name='trang_thai',
            field=models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đã đặt trước'), ('occupied', 'Đang sử dụng')], db_column='trang_thai', default='available', max_length=20),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='trang_thai',
            new_name='status',
        ),
    ]
